### PR TITLE
Use resources in translations?

### PR DESCRIPTION
**Pull request by gakada**
Items and ships are untranslated for me

With `resources` added to `poi-plugin-quest-info`

Though there are still cases like this

Also, that white on orange from [paperdark](https://github.com/poooi/poi-asset-themes/blob/master/dist/normal/paperdark.css)
```css
.panel-info > .panel-heading {
  color: #ffffff;
  background-color: #ffb90f;
  border-color: #ffe082;
}
```
looks like bad contrast (also according to https://webaim.org/resources/contrastchecker/).

### CODE REVIEW

**Comment by KagamiChan** [comment]
Are they not translated in current release or just current master HEAD?

`霞改二/改二乙` is related to source data, I've filed an issue there kcwikizh/kcdata#39

I've been planning a refactor of quest data parser, but did not get enough time for that, are you interested?

**Comment by gakada** [comment]
Hm, I think it was not translated on all stable/beta/HEAD, I've noticed prophet using `resources` in `getFixedT`, so just that fixed it for me (that is with translator plugin also enabled).

I'm interested, though I don't quite understand how it works or what needs to be done (or current activity here and on kcwikizh/kcdata). I still see `霞改二/改二乙` (after fetch) and more cases https://imgur.com/a/0KjimR3 (only checked A and B quests because that should be via a (semi-)automated test probably).

Also (current poi/plugin HEAD)

u

I guess that should be fixed with

```js
const translate = i18next.getFixedT(window.language, [
  'poi-plugin-quest-info',
  'resources',
])

const __ = (str, ...args) =>
  translate(str, ...args, {
    keySeparator: 'chiba', // there might be dots in item names
  })
```

in `index.es`?

**Comment by gakada** [comment]
Or maybe just in `RewardItem` for `name`.

**Comment by KagamiChan** [comment]
There'a a pending PR in data source, after it gets merged we could recheck. I know some of them should be corrected

At the beginning we tried to make quest detail human readable, so the parser will concatenate different requirements into a complete sentence. As time goes by, requirements for new quests become too complex to maintain. So we have to give up joining them, instead, they will be parsed as list.

For example:
`"Have Kinu Kai Ni as flagship and any 5 from Kitakami Kai Ni / Ooi Kai Ni / Kuma Kai / Aoba Kai / Uranami Kai / Shikinami Kai in your fleet"`

could become:
```
Organize a fleet that
- has Kinu Kai Ni as flagship
- has any 5 of the following
  + Kitakami Kai Ni
  + Ooi Kai Ni
  + Kuma Kai
  + Aoba Kai
  + Uranami Kai
  + Shikinami Kai
```

or more simple one:
```
Organize a fleet that
- Kinu Kai Ni as flagship
- any 5 from Kitakami Kai Ni / Ooi Kai Ni / Kuma Kai / Aoba Kai / Uranami Kai / Shikinami Kai
```

I'm not very sure if it is feasible and we will have many different forms to consider

**Comment by KagamiChan** [comment]
So from the point of view of an English user, which kind of requirement information is preferable?

**Comment by gakada** [comment]
Maybe it can be constructed as

```
Organize a fleet with Kinu Kai Ni as flagship and any 5 from Kitakami Kai Ni / Ooi Kai Ni / Kuma Kai / Aoba Kai / Uranami Kai / Shikinami Kai
```

with

```
print(requirements) = print(requirements.category) print(requirements.groups)
print(category = "fleet") = "Organize a fleet with"
print(groups) = map print over groups, slice all but last and join with ", ", join last with " and "
print(group = {ship, flagship}) = print(ship), add " as flagship" if flagship is true
print(group = {ship, select}) = "any {select} from " + ship, joined with " / "
```

so there is `,` and `and` for `groups` separator, and `/` for `ship` with `select`.

That is mostly like

```
Organize a fleet with
- Kinu Kai Ni as flagship
- any 5 from Kitakami Kai Ni / Ooi Kai Ni / Kuma Kai / Aoba Kai / Uranami Kai / Shikinami Kai
```

just different separators for `groups` (`,`/`and` vs `\n-`).

But that is just this one example, where I'd still go with sentences. I'm now considering using this data source for Wikia (so I can understand the problem better and because well it is pretty nice, those "semantic" requirements).

**Comment by KagamiChan** [comment]
That's similar to how current parser in the plugin works. The difference is that the result will not longer be a phrase but a new structure so that contents could be properly placed in different HTML tags (`<ul>` / `<li>` or something similar).

Seems you'll have to read through the parser code. let's make some general discussion first. If I find some time or motivation, I'll try to do the refactor because it also determines how poi will display them, then the problem could be more complex than I thought before.

I don't know if the wikia scripting environment natively supports something so-call `inflector`, or mainly pluralizing words according to given number. Without that, thing might become a little difficult

**Comment by KagamiChan** [comment]
btw, the data structure and parser code could not be Tanaka-complet, there's every now and then new quest that your data could not express, forcing you to update both

**Pull request merged**
