### PR TITLE
Chore/data

### PR DESCRIPTION
**Pull request by lawvs**
Try to use translations from [kcanotify-gamedata](https://github.com/antest1/kcanotify-gamedata)

> Translation data for ships, equipments and quest are mainly from kc3-translations.
License for kc3-translations: The MIT License Text
> --kcanotify

Thanks to [KC3Kai/kc3-translations](https://github.com/KC3Kai/kc3-translations) and @XxJimmy122xX  for their work!

<details>
<summary>Changelog</summary>

## Data

- Fix B144 type
- Update draft

### Features

- Add kcanotify translation
- Export `kcanotifyTranslation`

### Breaking Changes

- Prefer to use kcanotify translation
- Add `0`(Unknown) on `Quest.category` type

</details>

### CODE REVIEW

**Comment by KagamiChan** [comment]
If we stop using the quest object, can we download the data directly in this repo? in this way there's no delay for package release process

**Comment by KagamiChan** [comment]
I'm neutral for this change, just want to explore some possibilities to ship timely the new data

**Comment by XxJimmy122xX** [comment]
[kcanotify-gamedata](https://github.com/antest1/kcanotify-gamedata) is also used for Kcanotify to update in-app data. So it will always be up-to-date. Updates for new tasks useally take a day to a week. If you want faster update (like hours within task release), feel free to find me.

**Comment by KagamiChan** [comment]
Thanks @XxJimmy122xX, to avoid confusion, let me explain a little bit

From my understanding current process is:
1. `kcwiki-quest-data` downloads `kcanotify-gamedata` for translation
2. `kcwiki-quest-data` updates other quest info
3. new `kcwiki-quest-data` release
4. `poi-plugin-quest` updates `kcwiki-quest-data`
5. `poi-plugin-quest` release

What I want to optimize is the step 1, 3 and 4, as translation and quest reward/requirement is not depending each other now, `poi-plugin-quest` can download the `kcanotify-gamedata` and `kcwiki-quest-data` separately. In this way we'll show what's avaialble and no one needs to hurry

**Comment by lawvs** [comment]
> If we stop using the quest object, can we download the data directly in this repo? in this way there's no delay for package release process

Structured data is too complex to maintain (I haven't found any other i18n data source that has been maintained before), I'm planning to abandon `kcwiki-quest-data` and use `kcanotify-gamedata` on `plugin-quest` directly.

If switching to use `kcanotify-gamedata` then there are several questions:

- Whether  `kcanotify-gamedata` can be updated continuously
- We will lose most of the quest reward information
- We will lose structured information (hardly ever used)

**Comment by lawvs** [comment]
I forgot to specify that this update focuses on translations for poi's [task-panel](https://github.com/poooi/poi/blob/da75b507e8f67615a39dc4fdb466e34ff5b5bdcf/views/components/main/parts/task-panel.es#L239-L253)

image

**Comment by KagamiChan** [comment]
It is OK that we stop using the old quest data structure since it has become sophiscated and hard to maintain. I won't have any bad feelings for that.

To step forward, we can use a simpler structure for holding rewards and maybe quest dependencies

**Pull request merged**
