### PR TITLE
Merge data from KC3Kai

### PR DESCRIPTION
**Pull request by gakada**
Still need rendering, but the idea is that KC3Kai [file](https://raw.githubusercontent.com/KC3Kai/kc3-translations/master/data/en/quests.json) is merged in `data.json` and then users can have options to display something from it. `name` can be used as short translation/interpretation for quest titles (also in main program, since it is untranslated), `desc` and `memo` can be used as alternative requirements and rewards.

### CODE REVIEW

**Review by KagamiChan — COMMENTED** [review]
I'm afraid that I'm not going to merge this because:
- kc3kai data is not multilingual, we have to remove the data from kc3kai in languages other than English
- data format is kc3kai specific, it aims at within screen rendering, thus the description format is different and cannot be directly imported
- kc3kai i18n data updates quite frequently

It seems to me there's no much advantage in using this extra data source

**Comment by gakada** [comment]
- It is intended to work only with `en-US` (though there are [other](https://github.com/KC3Kai/kc3-translations/tree/master/data) languages as well, I'm not suggesting using them, at least not right now). Maybe instead of merging in `data.json` it can create a `en-US` file, used only when that language is selected.
- `desc` and `memo` yes (specific to screen rendering), though `name` field is rather short, simple and more generic, maybe at least that field can be used to translate/interpret quest titles? I don't know any other source for them. The advantage here is translating text which is currently untranslated. I think KC3Kai `name` strings were specially designed to display them in overview view (which they also have).
- Another advantage is some people may be more familiar with KC3Kai quest IDs.

**Comment by gakada** [comment]
Alternatively, [resources with context](https://gist.github.com/gakada/e02a1f362c9a95ca1179501b60f53c60), but here IDs will conflict with `wiki_id`.

**Comment by KagamiChan** [comment]
Title name seems to me a translation issue, putting them in translator is preferable, and as I pointed out before, poi's quest panel's normal size does not leave enough space for titles. I would suggest people directly read the description or search by the quest id on Internet

on quest id, I think wikis use the same id, the only difference is the number's zero padding, no way that kc3kai's numbering is different

**Comment by KagamiChan** [comment]
IMO the only standard for quest id is [wikiwiki's](https://wikiwiki.jp/kancolle/%E4%BB%BB%E5%8B%99), does current quest data id comply to it?

**Comment by gakada** [comment]
Well right now there is 3 mismatches
```
314 冬季大演習 kcwiki: C11, kc3kai: C14
622 機種転換 kcwiki: F20, kc3kai: F19
623 精鋭「九七式艦攻」部隊の編成 kcwiki: F19, kc3kai: F20
```

**Comment by KagamiChan** [comment]
c11 and c14 is a quest reusage from Tanaka, we could not tell which one is more correct

f20/f19 is a mistake from kcwiki

So it seems we don't need to keep 2 id system

**Comment by KagamiChan** [comment]
To summarize my point of view:
- quest name could be directly added to translator, although I don't think it could be informative
- I don't see much advantage importing kc3kai's description and memo unless we could have long term maintainers for reformulating texts in different languages, and even so I suggest improve the quest template
- quest id should follow wikiwiki's

**Comment by gakada** [comment]
We can assume that there is no ID conflicts, yes.

**Comment by gakada** [comment]
So is [this](https://gist.github.com/gakada/e02a1f362c9a95ca1179501b60f53c60) one acceptable for translator?

**Comment by gakada** [comment]
Though another option is to use "real" translations from English wikis.

**Comment by KagamiChan** [comment]
@gakada not quite in terms of "translation"

I don't really like 水雷戦隊」南西へ being translated to Monthly 1-4

**Comment by gakada** [comment]
Yeah, that one is interpretation, to make it look better in overview (instead of `Torpedo Squadron, Southwest Ho!` or something). Though with id like `Bm3` and a requirement tooltip real translation should be ok too. I guess this will have to wait until there are quest modules on wikia >_<

**Pull request closed without merging**
