### PR TITLE
Fix quest type filter width

### PR DESCRIPTION
**Pull request by gakada**
Since English strings can be longer

vs

### CODE REVIEW

**Comment by KagamiChan** [comment]
Seems we could simply omit the redundant `QUEST` for each category selection

**Comment by gakada** [comment]
On Lumendark skin that is still (without `Quest`)
u
So maybe both drop `Quest` and increase the width just a bit?

**Comment by KagamiChan** [comment]
Feel free to replace all occurrences of `QUEST`, e.g. replace all `Composition Quest` with `Composition`

**Comment by gakada** [comment]
I did https://github.com/poooi/plugin-quest/pull/49/commits/cedb151c26377efbf1964d8d22fe0a765b3cc0ec and https://github.com/poooi/plugin-quest/pull/49/commits/afab0c95bce9b1b0117b598fb784a8f5f301e04b. Or you want to switch `"Composition Quest"` _keys_ to `"Composition"`/etc., that would require editing i18n files for all languages as well as `index.es`.

**Comment by KagamiChan** [comment]
I'll go with the latter because we could remove the redundant `quest` from the origin, which is more definitive

**Comment by KagamiChan** [comment]
A project scope "find and replace" could make this in either VS Code or Atom. Or you could leave it to me if you use another editor

**Comment by gakada** [comment]
I'm using VS Code, I was just choosing between the two, the latter one is OK too.

**Comment by gnattu** [comment]
This does not seems to be a plugin or translation issue to me. This only happen to certain themes, because those themes uppercases all button texts, which makes the text significantly wider and exceeds the edge of the button.

LumenDark with default uppercase:
screen shot 2018-06-08 at 00 54 33

LumenDark without uppercase:
screen shot 2018-06-08 at 00 54 46

**Comment by gakada** [comment]
Still looks like this with no uppercase to me (paperdark)
u

**Comment by KagamiChan** [comment]
@gnattu anyway the `quest` could be removed to leave some space, at least that's not bad

**Comment by gakada** [comment]
Going to reopen.

**Pull request closed without merging**
